language: rust
rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf

script:
  cargo build --target armv7-unknown-linux-gnueabihf --verbose

install:
  rustup target add armv7-unknown-linux-gnueabihf