[package]
name = "ruspiro-boot"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.3" # remember to update html_root_url
description = ""
license = ""
repository = "https://github.com/RusPiRo/ruspiro-boot"
readme = ""
keywords = ["ruspiro", "raspberry-pi", "boot"]
categories = ["no-std"]
edition = "2018"

[lib]

[dependencies]

[features]
with_panic = []
with_exception = []
