[package]
name = "ruspiro-boot"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.3" # remember to update html_root_url
description = ""
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-boot/tree/v.0.0.3"
documentation = "https://docs.rs/ruspiro-boot/0.0.3"
readme = "README.md"
keywords = ["RusPiRo", "raspberrypi", "boot", "baremetal", "multicore"]
categories = ["no-std", "embedded"]
edition = "2018"

[lib]

[dependencies]

[features]
with_panic = []
with_exception = []
