[package]
name = "ruspiro-boot"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.2" # remember to update html_root_url
description = ""
license = "LICENSE"
repository = "https://github.com/RusPiRo/ruspiro-boot/tree/v.0.0.2"
readme = "README.md"
keywords = ["ruspiro", "raspberry-pi", "boot", "baremetal", "multicore"]
categories = ["no-std"]
edition = "2018"

[lib]

[dependencies]

[features]
with_panic = []
with_exception = []
