[package]
name = "ruspiro-boot"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.3" # remember to update html_root_url
description = ""
license = ""
repository = "https://github.com/RusPiRo/ruspiro-boot"
readme = ""
keywords = []
categories = []
edition = "2018"

[lib]

[dependencies]

[features]
